"""Bot version table

Revision ID: 01cffc7b13aa
Revises: b79635ca1431
Create Date: 2021-07-26 14:08:59.514980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01cffc7b13aa'
down_revision = 'b79635ca1431'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_version',
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('notification_sent', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('version'),
    sa.UniqueConstraint('version')
    )
    op.create_unique_constraint(None, 'privacy_terms_of_service', ['version'])
    op.create_unique_constraint(None, 'user', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'privacy_terms_of_service', type_='unique')
    op.drop_table('bot_version')
    # ### end Alembic commands ###
