"""changed bot_massage

Revision ID: c1f053f132a5
Revises: 3749eb38a020
Create Date: 2021-08-08 23:16:56.519442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1f053f132a5'
down_revision = '3749eb38a020'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_message',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('message_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('name'),
    sa.UniqueConstraint('message_id'),
    sa.UniqueConstraint('name')
    )
    op.drop_table('bot_messages')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_messages',
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('message_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('name', name='bot_messages_pkey'),
    sa.UniqueConstraint('message_id', name='bot_messages_message_id_key'),
    sa.UniqueConstraint('name', name='bot_messages_name_key')
    )
    op.drop_table('bot_message')
    # ### end Alembic commands ###
